[env:esp32dev]
platform = espressif32@~6.0.0
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    tzapu/WiFiManager@^2.0.17
    bblanchon/ArduinoJson@^7.4.1
    me-no-dev/ESPAsyncWebServer
    esp32async/AsyncTCP@^3.3.7
    mandulaj/PZEM-004T-v30
    knolleary/PubSubClient@^2.8

lib_extra_dirs = lib
board_build.partitions = partitions/ota.csv
board_build.filesystem = littlefs
